### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by ppasupat** [Farama-Foundation/miniwob-plusplus#58]
This is a loose roadmap of our plans for major changes to MiniWoB++:

**June:**

- Documentation
  - [ ] Write a guide for authoring new environments.
  - [ ] Document other properties of the environments such as reward function, time limit, etc.
  - [ ] Determine canonical sets of environments for comparable evaluation (e.g., in academic papers).
  - [ ] Demo usage with reinforcement learning.
- Code
  - [ ] Handle Unicode properly.

**July / August:**

- Code
  - [ ] Refactor Instance to support other backends than Selenium (e.g., X11).
- Environments
  - [ ] Add the missing tasks.
  - [ ] Add more FlightWoB-style tasks.
